
GET_SERVICE = 12
MY_CABINET = 11
GET_PASSWORD = 10
GET_LOGIN = 9
PHONE_SETTINGS = 8
NAME_SETTINGS = 7
LANG_SETTINGS = 6
ALL_SETTINGS = 5
CLICK_LANG = 4
SEND_CONTACT = 3 
SEND_NAME = 2 
SELECT_LANG = 1
